// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhqRxDeagN8SSW_E6Y9zjkJxchLpKVxuk',
    appId: '1:396257290892:web:55b248566f919d1be1e9a9',
    messagingSenderId: '396257290892',
    projectId: 'jal-rakshak-5ddf2',
    authDomain: 'jal-rakshak-5ddf2.firebaseapp.com',
    storageBucket: 'jal-rakshak-5ddf2.firebasestorage.app',
    measurementId: 'G-0Z2YYCYZMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUi_51jJtP2HkkuywijyI-fNUnM5WY_Tg',
    appId: '1:396257290892:android:969a0d8a83223e0ae1e9a9',
    messagingSenderId: '396257290892',
    projectId: 'jal-rakshak-5ddf2',
    storageBucket: 'jal-rakshak-5ddf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPO_Klpadd6j289pveInTf4yVqeNwK60',
    appId: '1:396257290892:ios:3d2c0cb734b45e06e1e9a9',
    messagingSenderId: '396257290892',
    projectId: 'jal-rakshak-5ddf2',
    storageBucket: 'jal-rakshak-5ddf2.firebasestorage.app',
    iosBundleId: 'com.example.prijectJalrakshak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPO_Klpadd6j289pveInTf4yVqeNwK60',
    appId: '1:396257290892:ios:3d2c0cb734b45e06e1e9a9',
    messagingSenderId: '396257290892',
    projectId: 'jal-rakshak-5ddf2',
    storageBucket: 'jal-rakshak-5ddf2.firebasestorage.app',
    iosBundleId: 'com.example.prijectJalrakshak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhqRxDeagN8SSW_E6Y9zjkJxchLpKVxuk',
    appId: '1:396257290892:web:ea2c1d0ee656ee91e1e9a9',
    messagingSenderId: '396257290892',
    projectId: 'jal-rakshak-5ddf2',
    authDomain: 'jal-rakshak-5ddf2.firebaseapp.com',
    storageBucket: 'jal-rakshak-5ddf2.firebasestorage.app',
    measurementId: 'G-X0DXFM8SSL',
  );
}
